# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  apt install wayland
  apt install wayland-libs-client
  apt install wayland-libs-cursor
  apt install wayland-libs-egl
  script:
    - make